version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network
    env_file:
      - ../.env

  api:
    build:
      context: ./api
    ports:
      - "7087:7087"
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - JWT__Issuer=http://localhost:7087
      - JWT__Audience=http://localhost:7087
      - JWT__SigningKey=${JWT_SIGNING_KEY}
      - FMPKey=${FMPKey}
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}

    depends_on:
      - sqlserver
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    env_file:
      - .env
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - ./api/data/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge
